import { heroui } from "@heroui/react";

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./node_modules/@heroui/theme/dist/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#d7e3fd",
        "error": "#ffb4ab",
        "surface-variant": "#293549",
        "surface-tint": "#adc6ff",
        "error-container": "#93000a",
        "tertiary-fixed-dim": "#ffb595",
        "tertiary-fixed": "#ffdbcc",
        "background": "#071326",
        "secondary-fixed-dim": "#00dce6",
        "on-error": "#690005",
        "outline": "#8b90a0",
        "surface-container-high": "#1e2a3e",
        "primary-container": "#4b8eff",
        "outline-variant": "#414755",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#d8e2ff",
        "on-tertiary-container": "#4c1a00",
        "primary-fixed-dim": "#adc6ff",
        "surface-container-low": "#0f1c2f",
        "surface-bright": "#2e3a4e",
        "on-secondary-fixed": "#002022",
        "on-tertiary-fixed": "#351000",
        "on-primary-fixed": "#001a41",
        "tertiary": "#ffb595",
        "surface": "#071326",
        "secondary": "#dcfdff",
        "on-secondary-fixed-variant": "#004f53",
        "on-surface-variant": "#c1c6d7",
        "on-primary-container": "#00285c",
        "inverse-on-surface": "#253145",
        "on-tertiary-fixed-variant": "#7c2e00",
        "secondary-fixed": "#6ff6ff",
        "on-primary": "#002e69",
        "on-background": "#d7e3fd",
        "on-surface": "#d7e3fd",
        "on-secondary-container": "#006a6f",
        "surface-dim": "#071326",
        "primary": "#adc6ff",
        "surface-container-highest": "#293549",
        "surface-container": "#142033",
        "tertiary-container": "#ef6719",
        "on-secondary": "#00373a",
        "surface-container-lowest": "#030e21",
        "on-primary-fixed-variant": "#004493",
        "inverse-primary": "#005bc1",
        "secondary-container": "#00f1fd",
        "on-tertiary": "#571e00",
      },
      fontFamily: {
        "label-mono-lg": ["JetBrains Mono"],
        "headline-sm": ["Inter"],
        "body-md": ["Inter"],
        "label-mono-sm": ["JetBrains Mono"],
        "label-mono-md": ["JetBrains Mono"],
        "body-lg": ["Inter"],
        "display-lg": ["Inter"],
        "headline-md": ["Inter"],
      },
      fontSize: {
        "label-mono-lg": ["16px", { lineHeight: "24px", fontWeight: "500" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-mono-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "label-mono-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
    },
  },
  plugins: [heroui()],
};
